"""SQLAlchemy declarative base and shared ORM conventions.

A single ``Base`` with an explicit constraint naming convention is what allows
Alembic to autogenerate migrations that can also be *downgraded* -- without it,
unnamed constraints get database-assigned names that migrations cannot target.
"""

from __future__ import annotations

import re
import uuid
from datetime import date, datetime, time
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    BigInteger,
    Date,
    DateTime,
    Identity,
    MetaData,
    Numeric,
    Time,
    Uuid,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

#: Deterministic names for indexes and constraints, required for reversible
#: Alembic migrations. ``ix`` = index, ``uq`` = unique, ``ck`` = check,
#: ``fk`` = foreign key, ``pk`` = primary key.
#:
#: Because every generated name is prefixed with its table, names are unique
#: across the schema -- which PostgreSQL requires, since unique constraints and
#: indexes share one namespace per schema. Passing an explicit ``name=`` to a
#: UniqueConstraint bypasses this and reintroduces the collision, so models
#: leave unique and foreign-key constraints unnamed. CHECK constraints are the
#: exception: their convention interpolates ``constraint_name``, so they are
#: named with the rule they enforce (``high_at_least_low``) and still come out
#: table-qualified.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

_CAMEL_TO_SNAKE = re.compile(r"(?<!^)(?=[A-Z])")


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model in the platform."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    #: Maps Python annotations to column types once, so no model has to repeat
    #: them. The important entry is ``Decimal`` -> ``NUMERIC``: prices and
    #: quantities must never round-trip through binary floating point, where
    #: 0.1 + 0.2 != 0.3 quietly corrupts returns and portfolio valuations.
    type_annotation_map = {  # noqa: RUF012 - SQLAlchemy reads this as a plain dict
        datetime: DateTime(timezone=True),
        date: Date(),
        time: Time(),
        Decimal: Numeric(20, 6),
        dict[str, Any]: JSONB,
    }

    @declared_attr.directive
    def __tablename__(cls) -> str:  # noqa: N805 - SQLAlchemy directive signature
        """Derive ``snake_case`` table names from ``CamelCase`` class names."""
        return _CAMEL_TO_SNAKE.sub("_", cls.__name__).lower()


class TimestampMixin:
    """Adds database-managed ``created_at`` / ``updated_at`` columns.

    Timestamps are generated by PostgreSQL rather than Python so that rows
    written by migrations, bulk ingestion jobs and the API all share one clock.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class IntIdMixin:
    """Surrogate ``BIGINT`` primary key generated by PostgreSQL.

    Used for internal and high-volume rows -- prices, indicators, anomalies --
    where a compact, sequential key keeps indexes small and range scans fast.
    ``Identity`` is the SQL-standard replacement for ``SERIAL``: the sequence is
    owned by the column, so it cannot be written to by accident.
    """

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=False), primary_key=True)


class UuidIdMixin:
    """Random ``UUID`` primary key generated by the application.

    Used for rows whose identifier is exposed to clients -- users and the
    objects they own. Sequential integers there would leak table size and let
    anyone enumerate accounts by counting upwards.
    """

    id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4)
