"""initial schema

Revision ID: efe849285eef
Revises:
Created: 2026-07-29 16:15:06.360305
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "efe849285eef"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True, comment="ISO 3166-1 alpha-2."),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=40)), server_default="{}", nullable=False
        ),
        sa.Column("is_tracked", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
        comment="Issuers tracked across the AI-infrastructure value chain.",
    )
    op.create_index("ix_company_sector", "company", ["sector"], unique=False)
    op.create_index(op.f("ix_company_slug"), "company", ["slug"], unique=True)
    op.create_index(
        "ix_company_tags_gin", "company", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "daily_market_summary",
        sa.Column("summary_date", sa.Date(), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "regime",
            sa.Enum("risk_on", "risk_off", "mixed", "quiet", name="market_regime"),
            nullable=False,
        ),
        sa.Column("advancers", sa.Integer(), server_default="0", nullable=False),
        sa.Column("decliners", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unchanged", sa.Integer(), server_default="0", nullable=False),
        sa.Column("average_return", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("anomaly_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "top_movers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "source_document_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("generated_by_model", sa.String(length=80), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_market_summary")),
        sa.UniqueConstraint("summary_date", name=op.f("uq_daily_market_summary_summary_date")),
        comment="Generated daily market briefings with their supporting statistics.",
    )
    op.create_table(
        "market_calendar",
        sa.Column("exchange", sa.String(length=30), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("is_trading_day", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("open_time", sa.Time(), nullable=True),
        sa.Column("close_time", sa.Time(), nullable=True),
        sa.Column("note", sa.String(length=120), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_calendar")),
        sa.UniqueConstraint("exchange", "session_date", name=op.f("uq_market_calendar_exchange")),
        comment="Per-exchange trading sessions and holidays.",
    )
    op.create_index(
        "ix_market_calendar_session_date", "market_calendar", ["session_date"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        comment="Platform user accounts.",
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "portfolio",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_portfolio_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_portfolio_user_id")),
        comment="User portfolios.",
    )
    op.create_index(op.f("ix_portfolio_user_id"), "portfolio", ["user_id"], unique=False)
    op.create_table(
        "ticker",
        sa.Column("company_id", sa.BigInteger(), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("exchange", sa.String(length=30), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column(
            "asset_type", sa.Enum("equity", "etf", "index", name="asset_type"), nullable=False
        ),
        sa.Column(
            "data_source",
            sa.Enum(
                "yfinance",
                "newsapi",
                "rss",
                "sec_edgar",
                "investor_relations",
                "manual",
                name="data_source",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("first_price_date", sa.Date(), nullable=True),
        sa.Column("last_price_date", sa.Date(), nullable=True),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(asset_type = 'equity' AND company_id IS NOT NULL) OR asset_type <> 'equity'",
            name=op.f("ck_ticker_equity_requires_company"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_ticker_company_id_company"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticker")),
        comment="Tradable listings; ETFs and indices have no parent company.",
    )
    op.create_index("ix_ticker_active_symbol", "ticker", ["is_active", "symbol"], unique=False)
    op.create_index(op.f("ix_ticker_company_id"), "ticker", ["company_id"], unique=False)
    op.create_index(op.f("ix_ticker_symbol"), "ticker", ["symbol"], unique=True)
    op.create_table(
        "watchlist",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_watchlist_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_watchlist_user_id")),
        comment="User-defined ticker collections.",
    )
    op.create_index(op.f("ix_watchlist_user_id"), "watchlist", ["user_id"], unique=False)
    op.create_table(
        "anomaly",
        sa.Column("ticker_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "anomaly_type",
            sa.Enum("return", "volume", "volatility", "gap", name="anomaly_type"),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum("z_score", "isolation_forest", name="detection_method"),
            nullable=False,
        ),
        sa.Column("direction", sa.Enum("up", "down", "neutral", name="direction"), nullable=False),
        sa.Column(
            "severity", sa.Enum("low", "medium", "high", "extreme", name="severity"), nullable=False
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("expected_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("deviation", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "related_document_ids",
            postgresql.ARRAY(sa.String(length=64)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_anomaly_confidence_is_a_ratio")
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["ticker.id"],
            name=op.f("fk_anomaly_ticker_id_ticker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomaly")),
        sa.UniqueConstraint(
            "ticker_id", "trade_date", "anomaly_type", "method", name=op.f("uq_anomaly_ticker_id")
        ),
        comment="Anomalies detected by the statistical and ML detectors.",
    )
    op.create_index("ix_anomaly_date_severity", "anomaly", ["trade_date", "severity"], unique=False)
    op.create_table(
        "daily_price",
        sa.Column("ticker_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "yfinance",
                "newsapi",
                "rss",
                "sec_edgar",
                "investor_relations",
                "manual",
                name="data_source",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("high >= low", name=op.f("ck_daily_price_high_at_least_low")),
        sa.CheckConstraint("volume >= 0", name=op.f("ck_daily_price_volume_non_negative")),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["ticker.id"],
            name=op.f("fk_daily_price_ticker_id_ticker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_price")),
        sa.UniqueConstraint("ticker_id", "trade_date", name=op.f("uq_daily_price_ticker_id")),
        comment="Daily OHLCV bars. Unique per (ticker, session).",
    )
    op.create_index("ix_daily_price_trade_date", "daily_price", ["trade_date"], unique=False)
    op.create_table(
        "portfolio_position",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("ticker_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "average_cost >= 0", name=op.f("ck_portfolio_position_average_cost_non_negative")
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_portfolio_position_quantity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
            name=op.f("fk_portfolio_position_portfolio_id_portfolio"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["ticker.id"],
            name=op.f("fk_portfolio_position_ticker_id_ticker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_position")),
        sa.UniqueConstraint(
            "portfolio_id", "ticker_id", name=op.f("uq_portfolio_position_portfolio_id")
        ),
        comment="Holdings within a portfolio.",
    )
    op.create_index(
        op.f("ix_portfolio_position_portfolio_id"),
        "portfolio_position",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_position_ticker_id"), "portfolio_position", ["ticker_id"], unique=False
    )
    op.create_table(
        "technical_indicator",
        sa.Column("ticker_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("daily_return", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("weekly_return", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("monthly_return", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sma_20", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sma_50", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("sma_200", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ema_12", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("ema_26", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("rsi_14", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("macd", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("macd_signal", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("macd_histogram", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("bollinger_upper", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("bollinger_middle", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("bollinger_lower", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("atr_14", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("volatility_20", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("volume_sma_20", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("volume_ratio", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("relative_strength_smh", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["ticker.id"],
            name=op.f("fk_technical_indicator_ticker_id_ticker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technical_indicator")),
        sa.UniqueConstraint(
            "ticker_id", "trade_date", name=op.f("uq_technical_indicator_ticker_id")
        ),
        comment="Derived technical features, one row per (ticker, session).",
    )
    op.create_table(
        "watchlist_item",
        sa.Column("watchlist_id", sa.Uuid(), nullable=False),
        sa.Column("ticker_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticker_id"],
            ["ticker.id"],
            name=op.f("fk_watchlist_item_ticker_id_ticker"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
            name=op.f("fk_watchlist_item_watchlist_id_watchlist"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_item")),
        sa.UniqueConstraint(
            "watchlist_id", "ticker_id", name=op.f("uq_watchlist_item_watchlist_id")
        ),
        comment="Ordered ticker membership within a watchlist.",
    )
    op.create_index(
        op.f("ix_watchlist_item_ticker_id"), "watchlist_item", ["ticker_id"], unique=False
    )
    op.create_index(
        op.f("ix_watchlist_item_watchlist_id"), "watchlist_item", ["watchlist_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_item_watchlist_id"), table_name="watchlist_item")
    op.drop_index(op.f("ix_watchlist_item_ticker_id"), table_name="watchlist_item")
    op.drop_table("watchlist_item")
    op.drop_table("technical_indicator")
    op.drop_index(op.f("ix_portfolio_position_ticker_id"), table_name="portfolio_position")
    op.drop_index(op.f("ix_portfolio_position_portfolio_id"), table_name="portfolio_position")
    op.drop_table("portfolio_position")
    op.drop_index("ix_daily_price_trade_date", table_name="daily_price")
    op.drop_table("daily_price")
    op.drop_index("ix_anomaly_date_severity", table_name="anomaly")
    op.drop_table("anomaly")
    op.drop_index(op.f("ix_watchlist_user_id"), table_name="watchlist")
    op.drop_table("watchlist")
    op.drop_index(op.f("ix_ticker_symbol"), table_name="ticker")
    op.drop_index(op.f("ix_ticker_company_id"), table_name="ticker")
    op.drop_index("ix_ticker_active_symbol", table_name="ticker")
    op.drop_table("ticker")
    op.drop_index(op.f("ix_portfolio_user_id"), table_name="portfolio")
    op.drop_table("portfolio")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_market_calendar_session_date", table_name="market_calendar")
    op.drop_table("market_calendar")
    op.drop_table("daily_market_summary")
    op.drop_index("ix_company_tags_gin", table_name="company", postgresql_using="gin")
    op.drop_index(op.f("ix_company_slug"), table_name="company")
    op.drop_index("ix_company_sector", table_name="company")
    op.drop_table("company")
    # ### end Alembic commands ###

    # Autogenerate creates the ENUM types implicitly with their tables but never
    # drops them: a downgrade would leave the types behind, and the next upgrade
    # would fail with "type already exists". Dropping them explicitly is what
    # makes this migration genuinely reversible.
    for enum_name in (
        "anomaly_type",
        "asset_type",
        "data_source",
        "detection_method",
        "direction",
        "market_regime",
        "severity",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
